language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION=2.6.*

before_script:
    - composer self-update
    - composer install
    - php bin/reload --domain=localhost --env=test

script:
  - phpunit -c app/
