services:
   sonata.admin.employee:
       class: AppBundle\Admin\EmployeeAdmin
       tags:
           - { name: sonata.admin, manager_type: orm, group: "Clinic", label: "Employees" }
       arguments:
           - ~
           - AppBundle\Entity\Employee
           - ~
       calls:
           - [ setTranslationDomain, [AppBundle]]

   sonata.admin.category:
       class: AppBundle\Admin\CategoryAdmin
       tags:
           - { name: sonata.admin, manager_type: orm, group: "Clinic", label: "Category" }
       arguments:
           - ~
           - AppBundle\Entity\Category
           - ~
       calls:
           - [ setTranslationDomain, [AppBundle]]
