services:
   sonata.admin.employee:
       class: AppBundle\Admin\EmployeeAdmin
       tags:
           - { name: sonata.admin, manager_type: orm, group: "Clinic", label: "Працівники" }
       arguments:
           - ~
           - AppBundle\Entity\Employee
           - ~
       calls:
           - [ setTranslationDomain, [messages]]

   sonata.admin.category:
       class: AppBundle\Admin\CategoryAdmin
       tags:
           - { name: sonata.admin, manager_type: orm, group: "Clinic", label: "Відділення" }
       arguments:
           - ~
           - AppBundle\Entity\Category
           - ~
       calls:
           - [ setTranslationDomain, [messages]]

   sonata.admin.post:
       class: AppBundle\Admin\PostAdmin
       tags:
           - { name: sonata.admin, manager_type: orm, group: "Clinic", label: "Публікації" }
       arguments:
           - ~
           - AppBundle\Entity\Post
           - ~
       calls:
           - [ setTranslationDomain, [messages]]

   sonata.admin.tag:
          class: AppBundle\Admin\TagAdmin
          tags:
              - { name: sonata.admin, manager_type: orm, group: "Hidden", label: "Теги" }
          arguments:
              - ~
              - AppBundle\Entity\Tag
              - ~
          calls:
              - [ setTranslationDomain, [messages]]


