app:
    resource: @AppBundle/Controller/
    type:     annotation

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: "%admin_dashboard_base_url%"

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: "%admin_dashboard_base_url%"

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

login:
  pattern:   /login
  defaults:  { _controller: AppBundle:Default:login }

login_check:
  pattern:   /login_check

logout:
   pattern: /logout