security:
  role_hierarchy:
      ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
      ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_SONATA_ADMIN, ROLE_ALLOWED_TO_SWITCH]

  firewalls:
      dev:
          pattern:  ^/(_(profiler|wdt)|css|images|js)/
          security: false

      secured_area:
          pattern:    ^/
          anonymous: ~
          form_login:
              login_path:  /login
              check_path:  /login_check
              default_target_path: homepage
          logout:
              path:   /logout
              target: /

  access_control:
      - { path: ^/admin, roles: ROLE_ADMIN }

  providers:
      in_memory:
          memory:
              users:
                  admin: { password: lOfMzCOlSxeQuieZYkW0g7k5kBQDs5NsbPrluozj0ezDwQKoopf745xgxUDmXA49VTKk/fDdWbKsSYeWU/WtRA==, roles: 'ROLE_ADMIN' }

  encoders:
      Symfony\Component\Security\Core\User\User: sha512