sonata_admin:
    title:      %sonata_admin.title%
    title_logo: %sonata_admin.logo_title%
    templates:
#      layout:  :SonataAdmin:base_layout.html.twig
      layout: ::SonataAdmin/standard_layout.html.twig
      edit: ::SonataAdmin/CRUD/edit.html.twig

    dashboard:
        groups:
            Clinic:
                label: Головна панель
                label_catalogue: AppBundle
            sonata_media:
                label: Медіа панель
                label_catalogue: AppBundle
#            Hidden:

        blocks:
            -
                position: left
                class: col-md-10
                type: sonata.admin.block.admin_list
                settings:
                    groups: [Clinic, sonata_media]
            -
                position: right
                class: col-md-6
                type: sonata.block.service.text
                settings:
                    content: >
                        <h3 style="text-align: center"><code>Вітаємо Вас в Адміністративній Панелі</code></h3>
                        <h4 style="text-align: center">П’ятої Черкаської міської поліклініки</h4>
                        <p style="text-align: center"><code>Контакти розробника:</code></p>
                        <p style="text-align: center"> Мушкін Віталій <code>+38(093)-977-77-01</code></p>
                        <p style="text-align: center">E-mail: <code>mushkin.v@gmail.com</code></p>

    assets:
        javascripts: # changed order of js assets loading
            - js/jquery-2.1.0.min.js
            - bundles/sonataadmin/vendor/jquery.scrollTo/jquery.scrollTo.min.js
            - bundles/sonatacore/vendor/moment/min/moment.min.js
            - bundles/sonataadmin/vendor/bootstrap/dist/js/bootstrap.min.js
            - bundles/sonatacore/vendor/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/jquery-ui.min.js
            - bundles/sonataadmin/vendor/jqueryui/ui/minified/i18n/jquery-ui-i18n.min.js
            - bundles/sonataadmin/jquery/jquery.form.js
            - bundles/sonataadmin/jquery/jquery.confirmExit.js
            - bundles/sonataadmin/vendor/x-editable/dist/bootstrap3-editable/js/bootstrap-editable.min.js
            - bundles/sonataadmin/vendor/select2/select2.min.js
            - bundles/sonataadmin/App.js
            - bundles/sonataadmin/Admin.js

sonata_doctrine_orm_admin:
    templates:
        form: [:SonataAdmin:form_admin_fields.html.twig]

